name: Forum

on:
  push:
    branches: [ master ]

jobs:
  Deploy:
    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21
      - name: Verify dependencies
        run: go mod verify
        
      - name: Build
        run: go build -o forum
        
      - name: Build & Deploy
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "forum"
          target: ${{ secrets.TARGET_DIR }}
    
      - name: SSH into EC2 and start the service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd ${{ secrets.TARGET_DIR }}
            export TMUX_TMPDIR=/tmp  # Set a temporary directory for tmux
            export TMUX=/usr/bin/tmux  # Specify the path to tmux executable

            tmux has-session -t my-session && tmux kill-session -t my-session
            tmux new-session -d -s my-session './forum'

